# Generated by Django 5.0.2 on 2024-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_form', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='final_marks',
            field=models.IntegerField(default=1),
        ),
    ]
